name: mimicmotion
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.7
  - pip
  - boto3
  - pip:
    - av==12.0.0
    - diffusers==0.27.0
    - transformers==4.32.1
    - decord==0.6.0
    - einops
    - omegaconf
    - clearml
    - boto3>=1.9
