name: Build and Push ClearML Docker Image

on:
  push:
    branches:
      - main  # Se ejecutará cuando haya cambios en la rama "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check if Dockerfile has changed
        id: dockerfile_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^Dockerfile$'; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        if: env.changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: env.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alejandroquinterosil/clearml-image:mimicmotion

      - name: Skip push (Dockerfile unchanged)
        if: env.changed == 'false'
        run: echo "No changes in Dockerfile. Skipping build and push."
